### ISSUE TITLE
Ximmio (Almere) doesnt work after update 2024.12.01

### ISSUE THREAD

**Issue by jonisnet** [xirixiz/homeassistant-afvalwijzer#327]
### The problem

After update to 2024.12.01 i don't recieve any device or entitie.

Tried to reinstall the repo, reboot Hass core and reload the integration with no succes.

### Version of afvalwijzer integration having the issue?

2024.12.01

### Version of Home Assistant Core having the issue?

2024.12.0

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:366
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 04:42:44 (3 gebeurtenissen)
Laatst gelogd: 14:49:35

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/afvalwijzer/sensor.py", line 57, in async_setup_entry
    await _setup_sensors(hass, entry.data, async_add_entities)
  File "/config/custom_components/afvalwijzer/sensor.py", line 77, in _setup_sensors
    await hass.async_add_executor_job(data.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 130, in update
    collector = MainCollector(
        provider,
    ...<6 lines>...
        default_label,
    )
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 98, in __init__
    waste_data_raw = ximmio.get_waste_data_raw(
        self.provider,
    ...<2 lines>...
        self.suffix,
    )
  File "/config/custom_components/afvalwijzer/collector/ximmio.py", line 36, in get_waste_data_raw
    uniqueId = response["dataList"][0]["UniqueId"]
               ~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by AussiSG** [comment]
Getting the same problems.... 
I think the main error is this:

`2024-12-06 18:57:25.032 ERROR (MainThread) [custom_components.afvalwijzer.const.const] No discovery information provided; sensors cannot be created.`

**Comment by marisvs** [comment]
I have the same problem as AussiSG and with exactly the same ERROR message after the Afvalwijzer update.

**Comment by AussiSG** [comment]
> I have the same problem as AussiSG and with exactly the same ERROR message after the Afvalwijzer update.

You can revert back to an earlier build:
https://github.com/xirixiz/homeassistant-afvalwijzer/issues/330#issuecomment-2524052546

**Comment by vincentkoevoets** [comment]
I missed the release note saying that you have to delete your current configuration of Afvalwijzer, and re-add it via Add integration flow. Info is here https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.12.01. Maybe you have missed it too?
Working for me again now.

**Comment by jonisnet** [comment]
> I missed the release note saying that you have to delete your current configuration of Afvalwijzer, and re-add it via Add integration flow. Info is here https://github.com/xirixiz/homeassistant-afvalwijzer/releases/tag/2024.12.01. Maybe you have missed it too?
> Working for me again now. 

No dienst mis that as said before.

**Comment by vincentkoevoets** [comment]
I cannot see where you said that before, but hey it's just a suggestion. There were 3 other issues here, all with the same error, and all were solved by manually deleting the previous _YAML configuration_ , meaning how we previously set up this integration. That YAML configuration has to be removed, Home Assistant restarted, and then the integration has to be added again by following the flow at Settings > Devices and services > Add integration.

**Comment by eleutscher** [comment]
Deleted all afval entitities
Deleted the integration Afvalwijzer
Deleted in HACS Afvalwijzer
Checked if under custom_components everything was deleted
Restarted HA
Download Afvalwijzer in HACS
Restart HA
Add Afvalwijzer and went to the config (Ximmio) and still not working

**Comment by vincentkoevoets** [comment]
Okay, if I'm reading this right, you still missed the step of actually deleting the previous yaml configuration in either you HA configuration.yaml or a seperate file (in my case I have ``` sensor: !include_dir_merge_list sensors ``` in my HA configuration.yaml, and the file for Afvalwijzer is called sensors/afvalwijzer.yaml). The old config you're looking for looks like this:
```
- platform: afvalwijzer
  provider: <provider>
  postal_code: <postal code> 
  street_number:  <street number>
  suffix: '' 
  exclude_pickup_today: false 
  default_label: Geen 
  id: '' 
  exclude_list: '' 
```
Hope this helps.

**Comment by eleutscher** [comment]
I made sure there were no entries in the sensors.yaml or configuration.yaml
Strange thing is, if I select prezero as an Provider it will create 6 sensors but with no data. If I select ximmio it will not create anything

**Comment by vincentkoevoets** [comment]
Hmm then at least we're sure the old config is gone. Then I'm out of options, let's hope the dev will take a look at it then.

**Comment by eleutscher** [comment]
Could it be because of new version Python? 
The error that I see is TypeError: 'NoneType' object is not subscriptable and this relates to Python.
I had simulair erros with my Garmin integration and that also was related to new version Python

**Comment by xirixiz** [comment]
Hi, this is odd. Somehow I missed all open issues. I just got a new laptop and suddenly a lot of open issues are visible. I`ll have a look and come back to it asap. Thanks!

**Comment by eleutscher** [comment]
I now get a different error selecting ximmio as waste provider for Almere. 

First Address not found!

Second 
Logger: homeassistant.components.sensor
Bron: helpers/entity_platform.py:366
integratie: Sensor (documentatie, problemen)
Eerst voorgekomen: 14:48:56 (4 gebeurtenissen)
Laatst gelogd: 19:34:54

Error while setting up afvalwijzer platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/afvalwijzer/sensor.py", line 57, in async_setup_entry
    await _setup_sensors(hass, entry.data, async_add_entities)
  File "/config/custom_components/afvalwijzer/sensor.py", line 77, in _setup_sensors
    await hass.async_add_executor_job(data.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalwijzer/sensor.py", line 134, in update
    collector = MainCollector(
        provider,
    ...<6 lines>...
        default_label,
    )
  File "/config/custom_components/afvalwijzer/collector/main_collector.py", line 138, in __init__
    self._waste_data = WasteDataTransformer(
                       ~~~~~~~~~~~~~~~~~~~~^
        waste_data_raw,
        ^^^^^^^^^^^^^^^
    ...<2 lines>...
        self.default_label,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/afvalwijzer/common/waste_data_transformer.py", line 25, in __init__
    waste_data_raw.sort(key=lambda item: datetime.strptime(item["date"], "%Y-%m-%d"))
    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sort'


But Ximmio is the waste provider for Almere. See https://modules.ximmio.com/?companyCode=53d8db94-7945-42fd-9742-9bbc71dbe4c1&moduleName=calendarGeneric
